# Welcome to Jekyll!
#

# Site settings
title: 아멜리에 2134
description: |
선물, 꽃, 가드닝, 카페
owner: Amelie # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: amelie2134@naver.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.amelie2134.co.kr" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: http://facebook.com/amelie2134
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: amelie2134@naver.com
  #flickr:
  instagram: http://instagram.com/amelie2134_
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
